import { describe, expect, it } from "vitest";
import { matchOccupation } from "./occupation";

const cases: [string, string | null][] = [
  ["Senior Software Engineer", "2134"],
  ["Data Scientist/Software Engineer (AI and Computer Vision)", "2134"],
  ["Backend Engineer III", "2134"],
  ["Machine Learning Engineer", "2134"],
  ["Data Scientist", "2433"],
  ["Data Engineer", "2133"],
  ["Solutions Architect", "2133"],
  ["Integration Engineer", "2139"],
  ["DevOps Engineer", "2139"],
  ["Cyber Security Analyst", "2135"],
  ["Network Engineer", "2137"],
  ["QA Engineer", "2136"],
  ["Data Analyst", "3544"],
  ["Product Designer", "2141"],
  ["Engineering Manager", "2132"],
  ["IT Project Manager", "2131"],
  ["Rehabilitation Engineer", "2129"],
  ["Medical Engineer", "2129"],
  ["Civil Engineer", "2121"],
  ["Mechanical Design Engineer", "2122"],
  ["Power Systems Engineer", "2123"],
  ["Electronics Engineer", "2124"],
  ["Staff Nurse", "2237"],
  ["Registered Nurse - Band 5", "2237"],
  ["Clinical Nurse Specialist", "2233"],
  ["Community Mental Health Nurse", "2235"],
  ["Paediatric Nurse", "2236"],
  ["District Nurse", "2232"],
  ["Advanced Nurse Practitioner", "2234"],
  ["Midwife", "2231"],
  ["Healthcare Assistant", "6131"],
  ["Consultant Psychiatrist", "2212"],
  ["Specialty Doctor in Emergency Medicine", "2212"],
  ["Salaried GP", "2211"],
  ["Pharmacist", "2251"],
  ["Physiotherapist (Band 6)", "2221"],
  ["Occupational Therapist", "2222"],
  ["Speech and Language Therapist", "2223"],
  ["Clinical Psychologist", "2225"],
  ["Radiographer", "2254"],
  ["Sonographer", "2254"],
  ["Paramedic", "2255"],
  ["Dietitian", "2259"],
  ["Biomedical Scientist", "2113"],
  ["Clinical Scientist", "2113"],
  ["Management Accountant", "2421"],
  ["Credit Analyst", "2422"],
  ["Business Analyst", "2133"],
  ["Marketing Manager", "2432"],
  ["Quantity Surveyor", "2453"],
  ["Architect", "2451"],
  ["Teacher of Mathematics", "2313"],
  ["Primary Teacher", "2314"],
  ["Lecturer in Computer Science", "2311"],
  ["Service Manager", "1171"],
  ["Care Assistant", "6135"],
  ["Sous Chef", "5434"],
  ["Anaplan Support Analyst", null],
  ["Senior Legal Counsel, Digital Assets and Payments", "2412"],
  ["Operational Tax, Senior Manager", "2423"],
  ["Director of Product Design", "1139"],
  ["Director of Fleet Operations Execution", "1139"],
  ["Data Science Manager", "2132"],
  ["Receptionist", null],
];

describe("matchOccupation", () => {
  it.each(cases)("%s → %s", (title, soc) => {
    expect(matchOccupation(title)).toBe(soc);
  });
});
